services:
  apigw:
    path: services/apigw
  catches-api:
    path: services/catches-api
    depends_on:
      - apigw
  media-api:
    path: services/media-api
    depends_on:
      - apigw
  website:
    path: services/website
    depends_on:
      - apigw
