version: '3'
services:
  storybook:
    image: node:16
    command: bash -c "npm install && chmod -R a+rw node_modules && npm run storybook"
    working_dir: /workspace
    volumes:
      - .:/workspace
      - ./docker/storybook/package-lock.json:/workspace/package-lock.json
      - node-cache:/workspace/node_modules
    ports:
      - 6006:6006

volumes:
  node-cache:
