service: fishing-logger-catches-api
frameworkVersion: "3"

plugins:
  - serverless-webpack

custom:
  webpack:
    includeModules:
      forceExclude:
        - aws-sdk
      nodeModulesRelativeDir: "../../"
    packagerOptions:
      lockFile: "../../package-lock.json"

package:
  individually: true

provider:
  name: aws
  region: ap-northeast-1
  runtime: nodejs16.x
  lambdaHashingVersion: "20201221"
  environment:
    DYNAMODB_TABLE: ${self:service}-${sls:stage}
  httpApi:
    id: !ImportValue sls-fishing-logger-apigw-${sls:stage}-HttpApiId
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  create:
    handler: src/functions/create.create
    events:
      - httpApi:
          path: /api/catches
          method: post

  add-media:
    handler: src/functions/add-media.addMedia
    events:
      - httpApi:
          path: /api/catches/{id}/media
          method: post

  list:
    handler: src/functions/list.list
    events:
      - httpApi:
          path: /api/catches
          method: get

  get:
    handler: src/functions/get.get
    events:
      - httpApi:
          path: /api/catches/{id}
          method: get

  update:
    handler: src/functions/update.update
    events:
      - httpApi:
          path: /api/catches/{id}
          method: put

resources:
  Resources:
    CatchesDynamoDbTable:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
