service: catches-api
frameworkVersion: "3"

useDotenv: true

plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-common-excludes # this should go before serverless-plugin-include-dependencies
  - serverless-plugin-include-dependencies

provider:
  name: aws
  runtime: nodejs16.x
  lambdaHashingVersion: "20201221"
  environment:
    DYNAMODB_TABLE: ${self:service}-${sls:stage}
  httpApi:
    cors: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  create:
    handler: src/functions/create.create
    events:
      - httpApi:
          path: /api/catches
          method: post

  list:
    handler: src/functions/list.list
    events:
      - httpApi:
          path: /api/catches
          method: get

  get:
    handler: src/functions/get.get
    events:
      - httpApi:
          path: /api/catches/{id}
          method: get

  update:
    handler: src/functions/update.update
    events:
      - httpApi:
          path: /api/catches/{id}
          method: put

resources:
  Resources:
    CatchesDynamoDbTable:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
